# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# Before running goreleaser create a tag and push it:
#  - git tag -a v0.2.0 -m "Adding Docker to the publish"
#  - git push origin v0.2.0

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
    # go test all
    # - go test -cover -race ./...
builds:
  -
    main: ./app/main.go
    binary: jsonify
    env:
      - CGO_ENABLED=0

    goos:
      - darwin
      - linux

    goarch:
      - amd64
      - arm
      - arm64

archives:
  - id: archive_names
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

