# To create a github access token - Go to Profile > Settings > Developer Settings > Github Access Tokens
name: Pull Request

# Run on all branches except `main` (since that it should have been run pre-merge)
on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  release:
    name: Run Pull Request Tests
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Environment
        run: |
          echo CGO_ENABLED=1 >> $GITHUB_ENV
          sudo apt update
          sudo apt install -y libgl1-mesa-dev xorg-dev

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'

      - name: Run Tests
        run: go test -race ./...
