# To create a github access token - Go to Profile > Settings > Developer Settings > Github Access Tokens
name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "New Build Tag (eg. 0.0.1)"
        required: true

jobs:
  tag:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: '0'

      - name: Print Input
        run: echo "${{ inputs.tag }}"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          WITH_V: true
          CUSTOM_TAG: "v${{ inputs.tag }}"

  goreleaser:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - run: go version

      - name: Install Core
        run: go install cogentcore.org/core/cmd/core@main

      - name: Build App arm64
        run: core build darwin/arm64 -name jsonify_arm64/jsonify -dir app

      - name: ⏫ Upload arm64 build
        uses: nmerget/upload-gzip-artifact@main
        with:
          name: jsonify_arm64
          path: jsonify_arm64

