# To create a github access token - Go to Profile > Settings > Developer Settings > Github Access Tokens
name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "New Build Tag (eg. 0.0.1)"
        required: true

permissions:
  contents: write

jobs:
  release:
    name: Release Version "${{ inputs.tag }}"
    runs-on: 'macos-latest'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'

      - name: Set up Core
        run: go install cogentcore.org/core/cmd/core@main && core setup

      - name: Run Tests
        run: go test ./...

      # -C forces the Go compiler to change directories before running, and it can only find the Go files if
      # it's in the `app` folder.  So after building we use the `-o ../` command to force it to place the
      # resulting binary back in the original directory of the shell.  So we can process the subsequent commands
      # from there.
      - name: Build
        run: |
          CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -C ./app -o ../jsonify && chmod 755 jsonify && gzip jsonify && mv jsonify.gz jsonify_amd64.gz
          CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -C ./app -o ../jsonify && chmod 755 jsonify && gzip jsonify && mv jsonify.gz jsonify_arm64.gz

      - name: Set Release Notes
        run: |
          git pull --tags
          newestTaggedCommit="$(git rev-list --tags --max-count=1)"
          git log $(git describe HEAD~ --tags "$newestTaggedCommit" --abbrev=0)..HEAD --pretty='format:* %h %s%n  * %an <%ae>' --no-merges >> ".github/RELEASE-TEMPLATE.md"

      - name: Tag branch
        run: |
          git tag -f -a v${{ inputs.tag }} -m "Release v${{ inputs.tag }}"
          git push -f origin v${{ inputs.tag }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ inputs.tag }}"
          name: "v${{ inputs.tag }}"
          body_path: ".github/RELEASE-TEMPLATE.md"
          files: |
            jsonify_amd64.gz
            jsonify_arm64.gz
